### ISSUE TITLE
Eliminate redundancy in AZURE_CREDENTIALS secret

### ISSUE THREAD

**Issue by mike-schenk** [im-practices/.github#41]
https://github.com/im-practices/.github/blob/9e03dbfde8458947d5e084556651b2220b309b00/workflow-templates/im-deploy-az-app-service-manually.yml#L211

To reduce the number of secrets to manage, I suggest we don't set AZURE_CREDENTIALS as a GitHub secret. Instead, the `creds` input to `azure/login` should be constructed from the other secrets as follows:

```
env:
  AZURE_CREDENTIALS: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
          # optional:
          # "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
          # "resourceManagerEndpointUrl": "https://management.azure.com/",
          # "activeDirectoryGraphResourceId": "https://graph.windows.net/",
          # "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
          # "galleryEndpointUrl": "https://gallery.azure.com/",
          # "managementEndpointUrl": "https://management.core.windows.net/"
  ...
  uses: azure/login@v1
  with:
    creds: ${{ env.AZURE_CREDENTIALS }}
```

Note that most of the values that are currently set in the AZURE_CREDENTIALS secret are actually fixed values matching the default values. They're only necessary when targeting a specific Azure cloud (e.g. China, USGovernment, Azure stack, etc.).

Or even without using another environment variable:

```
  uses: azure/login@v1
  with:
    creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
```

**Comment by danielle-casella-adams** [comment]
I know the default urls that are included shouldn't matter but they seem to.  When developing the workflows, I had lots of flakiness around the az login when using a json object that does not contain the additional urls.  When I switched over to the full object things were stable again and I didn't have those intermittent errors.

**Comment by bradyclifford** [comment]
I would like to see this change as well.  This would go well with #42.

**Comment by mike-schenk** [comment]
We're no longer maintaining AZURE_CREDENTIALS secrets in GitHub. This is now out-of-date.
