### ISSUE TITLE
Idea: Azure service principal secrets at the GitHub organization level

### ISSUE THREAD

**Issue by mike-schenk** [im-practices/.github#42]
Here are two things that bother me about how Azure service principal secrets are held in GitHub now.

1. Our team's Demo environment currently deploys using the Stage service principal and will eventually use the Prod service principal. The automatic credential rotation pipeline doesn't know how to push the stage secrets to our "Demo" GitHub environment. Similarly, we may want to use unique environment names that share an Azure service principal with one of the 'standard' environment names. In other words, the mapping of service principals to environments is not strictly 1-to-1.
2. Every time our Terraform plan workflow runs, GitHub reports that the build was "deployed" to Dev. This is due to [the mere reference of an environment](https://docs.github.com/en/actions/reference/environments#referencing-an-environment) name in a job. I would much rather GitHub reports a deployment only when we actually deploy.

As Azure service principal secrets get assigned and rotated, what if we had them stored as organization secrets instead of environment secrets like this?

| Org | Name | Value |
| --- | --- | --- |
| im-enrollment | BDAIM_D_NA26_AccountManagement_SP_ClientID |  _the clientId of the named service principal_ |
| im-enrollment | BDAIM_D_NA26_AccountManagement_SP_Secret |  _the clientSecret of the named service principal_ |
| im-enrollment | BDAIM_Q_NA26_AccountManagement_SP_ClientID |  _the clientId of the named service principal_ |
| im-enrollment | BDAIM_Q_NA26_AccountManagement_SP_Secret |  _the clientSecret of the named service principal_ |
| ... other envs ...
| im-enrollment | BDAIM_P_NA26_AccountManagement_SP_ClientID |  _the clientId of the named service principal_ |
| im-enrollment | BDAIM_P_NA26_AccountManagement_SP_Secret |  _the clientSecret of the named service principal_ |
| ... other orgs ...
| im-client | BDAIM_D_NA26_ClientData_SP_ClientID |  |
| im-client | BDAIM_D_NA26_ClientData_SP_Secret |  |
| ... other envs ...
| im-client | BDAIM_P_NA26_ClientData_SP_ClientID |  |
| im-client | BDAIM_P_NA26_ClientData_SP_Secret |  |
| ... other orgs ...
| im-practices | BDAIM_D_NA26_CentralLogging_SP_ClientID | |
| im-practices | BDAIM_D_NA26_CentralLogging_SP_Secret | |

I think this has these advantages:

* Fewer secrets to manage overall: note that tenant ID and subscription id are not secrets and are pretty much fixed values. They can be included directly in workflow definitions.
* The name of the variable tells you which service principal it represents.
* We would be able to run Terraform Validate and Plan actions without causing GitHub to report that the PR was "deployed" to a given environment.
* We would be able to add GitHub repositories that use existing service principals without having to retrieve and duplicate secrets, and without having to force the secret-publishing pipeline to run again.
* Our workflows would be able to use secrets of more than one environment in the same job.
* No need for the secret-rotating-publishing pipeline to map service principal name patterns to environment names, which leaves teams free to define their own GitHub environments.

The disadvantages:

* GitHub's Environment protection rules wouldn't protect the prod secrets.
  * This is a two-edged sword. The protection is nice and I want to prevent an actual _deployment_ to Prod from a branch, but I'd like to run a Terraform Plan against prod from a branch before I merge it to main.
* The workflows have to map from these secrets to the ARM_* environment variables the Terraform `azurerm` backend expects.
* There will be a long list of secrets in each organization
* Organization admins have to manage which repositories are allowed access to which secrets. And I don't know if there's any traceability of those kinds of changes.

## Alternatives
* Maybe only set one GitHub secret per service principal. Its name would be the SP name and it's value would be its clientSecret. Workflows would have to hold the corresponding clientIds.
* Maybe set one GitHub secret per service principal but its name would be the clientID (modified to fit the rules of GitHub secret names) and its value would be the clientSecret. Workflows would 'know' the clientIDs they need so they can retrieve the right secret.
* Maybe set secrets like these at the Repository level instead of the Organization or Environment level where they can be re-used across different Environments.
* Maybe adjust the pipeline that pushes secrets to GitHub so that we can tell it not only which GitHub repositories to push to (through tags), but _also which environment(s)_ in those repositories.

**Comment by bradyclifford** [comment]
As a note we also get emails about a "deployment" when stakeholder and attestor approvals are performed.  Probably not a way around that.

**Comment by jsclifford** [comment]
Since the Federated credentials is the new standard, is this issue going away?

**Comment by mike-schenk** [comment]
Yeah, I think this issue can go away.

We're still left with GitHub's limitation that every job that references any environment reports a deployment, but we've accepted that limitation now too with our custom deployment reporting.
